export const FILTER_AVAILABLE_STOCKS = 'FILTER_AVAILABLE_STOCKS';
export const UPDATE_PORTFOLIO = 'UPDATE_PORTFOLIO';
export const UPDATE_AVAILABLE = 'UPDATE_AVAILABLE';
export const SORT_AVAILABLE_STOCKS = 'SORT_AVAILABLE_STOCKS';
export const SORT_PORTFOLIO_STOCKS = 'SORT_PORTFOLIO_STOCKS';
